// Copyright Epic Games, Inc. All Rights Reserved.


#include "TestForMinigamePlayerController.h"
#include "EnhancedInputSubsystems.h"
#include "Engine/LocalPlayer.h"
#include "InputMappingContext.h"
#include "Blueprint/UserWidget.h"
#include "TestForMinigame.h"
#include "Widgets/Input/SVirtualJoystick.h"
#include "TestForMinigameGameState.h"
#include "Engine/Engine.h"

ATestForMinigamePlayerController::ATestForMinigamePlayerController()
{
	bReplicates = true;
}

void ATestForMinigamePlayerController::BeginPlay()
{
	Super::BeginPlay();

	// åªæœ‰æœ¬åœ°çš„PlayerControlleræ‰ç»‘å®šäº‹ä»¶
	if (IsLocalPlayerController())
	{
		UE_LOG(LogTemp, Warning, TEXT("æœ¬åœ°PlayerControllerç»‘å®šäº‹ä»¶"));

		if (ATestForMinigameGameState* GS = GetWorld()->GetGameState<ATestForMinigameGameState>())
		{
			GS->OnInsightValueChanged.AddDynamic(this, &ATestForMinigamePlayerController::OnInsightChanged);
			GS->OnEnterPhaseTwo.AddDynamic(this, &ATestForMinigamePlayerController::OnPhaseTwo);
		}
	}
	else
	{
		UE_LOG(LogTemp, Log, TEXT("éæœ¬åœ°PlayerControllerï¼Œè·³è¿‡äº‹ä»¶ç»‘å®š"));
	}

	// only spawn touch controls on local player controllers
	if (SVirtualJoystick::ShouldDisplayTouchInterface() && IsLocalPlayerController())
	{
		// spawn the mobile controls widget
		MobileControlsWidget = CreateWidget<UUserWidget>(this, MobileControlsWidgetClass);

		if (MobileControlsWidget)
		{
			// add the controls to the player screen
			MobileControlsWidget->AddToPlayerScreen(0);

		} else {

			UE_LOG(LogTestForMinigame, Error, TEXT("Could not spawn mobile controls widget."));

		}

	}
}

void ATestForMinigamePlayerController::SetupInputComponent()
{
	Super::SetupInputComponent();

	// only add IMCs for local player controllers
	if (IsLocalPlayerController())
	{
		// Add Input Mapping Contexts
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem = ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(GetLocalPlayer()))
		{
			for (UInputMappingContext* CurrentContext : DefaultMappingContexts)
			{
				Subsystem->AddMappingContext(CurrentContext, 0);
			}

			// only add these IMCs if we're not using mobile touch input
			if (!SVirtualJoystick::ShouldDisplayTouchInterface())
			{
				for (UInputMappingContext* CurrentContext : MobileExcludedMappingContexts)
				{
					Subsystem->AddMappingContext(CurrentContext, 0);
				}
			}
		}
	}
}

void ATestForMinigamePlayerController::ServerAddInsightValue_Implementation(int32 Amount)
{
	UE_LOG(LogTemp, Warning, TEXT("PlayerController Server RPC æ‰§è¡Œï¼Amount = %d"), Amount);

	// åœ¨æœåŠ¡å™¨ä¸Šæ‰§è¡Œï¼Œç›´æ¥æ“ä½œGameState
	if (ATestForMinigameGameState* GS = GetWorld()->GetGameState<ATestForMinigameGameState>())
	{
		int32 OldValue = GS->GlobalInsightValue;
		GS->GlobalInsightValue = FMath::Clamp(GS->GlobalInsightValue + Amount, 0, GS->MaxInsightValue);

		UE_LOG(LogTemp, Warning, TEXT("PlayerControllerä¿®æ”¹çµè§†å€¼: %d -> %d"), OldValue, GS->GlobalInsightValue);

		// æ£€æŸ¥é˜¶æ®µè½¬æ¢
		if (GS->GlobalInsightValue >= GS->MaxInsightValue && !GS->bIsPhaseTwo)
		{
			GS->bIsPhaseTwo = true;
			GS->MulticastEnterPhaseTwo();
			UE_LOG(LogTemp, Error, TEXT("é€šè¿‡PlayerControllerè¿›å…¥äºŒé˜¶æ®µï¼"));
		}

		// å¤šæ’­UIæ›´æ–°
		GS->MulticastUpdateUI(OldValue, GS->GlobalInsightValue);
	}
}

void ATestForMinigamePlayerController::OnInsightChanged(int32 NewValue, int32 OldValue)
{
	if (GEngine)
	{
		FString Message = FString::Printf(TEXT("Controlleræ”¶åˆ°çµè§†å€¼å˜åŒ–: %d -> %d"), OldValue, NewValue);
		GEngine->AddOnScreenDebugMessage(-1, 3.0f, FColor::Cyan, Message);
	}

	UE_LOG(LogTemp, Log, TEXT("PlayerControlleræ”¶åˆ°çµè§†å€¼å˜åŒ–: %d -> %d"), OldValue, NewValue);
}

void ATestForMinigamePlayerController::OnPhaseTwo()
{
	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.0f, FColor::Red, TEXT("ğŸ”¥ PlayerControlleræ”¶åˆ°äºŒé˜¶æ®µé€šçŸ¥ï¼ğŸ”¥"));
	}

	UE_LOG(LogTemp, Error, TEXT("PlayerControlleræ”¶åˆ°äºŒé˜¶æ®µé€šçŸ¥ï¼"));
}